name: Deploy to GH-pages

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        strategy:
            matrix:
                node-version: [17.x]
        defaults:
            run:
                working-directory: ./frontend

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Patch index.tsx to use HashRouter for Github Pages support
              run: sed 's/BrowserRouter/HashRouter/' src/index.tsx -i

            - name: Build using yarn script
              run: |
                  yarn set version stable
                  yarn install
                  yarn run build --if-present

            - name: Deploy to gh-pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  cname: dev.dimensioncubed.xyz
                  publish_dir: ./frontend/build
